### PR TITLE
Modified the .tlef file to address issues #308 & #312

### PR DESCRIPTION
**Pull request by egiacomin**
These small changes will fix issues [308](https://github.com/google/skywater-pdk/issues/308) and [312](https://github.com/google/skywater-pdk/issues/312) regarding the .tlef file of the library.

If these changes are approved, I can ahead the other libraries.

### CODE REVIEW

**Comment by egiacomin** [comment]
Hi @mithro , is there any particular reason why this PR was closed?

**Comment by mithro** [comment]
It looks like when renaming the branch from `master` to `main` GitHub automatically closed this pull request.

The team is still working on the system for enabling pull requests to be merged into the PDK and hopefully we will have a solution soon.

**Comment by mithro** [comment]
As the master branch no longer exists, it looks like you will have to resend the pull request again the main branch.

**Comment by egiacomin** [comment]
@mithro Got it, thanks for the clarification. I just sent another PR to the main branch.

**Pull request closed without merging**
